baseURL = "/"
languageCode = "en-us"
title = "Empty Coffee"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"

  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = true

  addFrame = false
  addDot = false

  highlightColor = '#1A202C'